/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2938ce7b-1461-4a95-9d6c-68ec9f077754",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xENviSMMb",
    "aws_user_pools_web_client_id": "5fcm4s0ok0krgb7o7a69s8jlsm",
    "oauth": {}
};


export default awsmobile;
